// Build the review page that ships inside the upload folder.
//
// WHY IT LIVES HERE. I wrote this page by hand into the packaged folder once,
// and the next `package-upload` run deleted it — the folder is rebuilt from
// scratch every time, so anything not generated by the packer disappears. He
// opened the link and got ERR_FILE_NOT_FOUND. A page he is meant to keep
// opening has to be produced by the same step that produces the folder, or it
// is gone the moment anything is rebuilt.
//
// It is also always current for the same reason: the captions and the frame
// count come from the specs the packer just read, not from whatever was true
// when someone wrote the page.

const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => (
  { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

/**
 * @param {Array<{deck:string,n:number,title:string,caption:string,tags:string}>} decks
 * @param {number} contentSlides how many frames are ours before his closing pair
 */
export function viewerHtml(decks, { onlyNew = false } = {}) {
  const sections = decks.map((d) => `
  <section>
    <h2>${esc(d.title)}</h2>
    <p class="meta">${esc(d.deck)} · ${d.n} שקופיות</p>
    <div class="cap">${esc(d.caption)}

<b>${esc(d.tags)}</b></div>
    <div class="strip">${
      Array.from({ length: d.n }, (_, i) => {
        const nn = String(i + 1).padStart(2, '0');
        // The last two are his own closing pair, copied rather than rendered,
        // and are marked so the page does not read as if we made them.
        const own = i >= d.n - 2;
        return `<figure${own ? ' class="own"' : ''}>`
          + `<a href="${esc(d.deck)}/${nn}.jpg" target="_blank">`
          + `<img src="${esc(d.deck)}/${nn}.jpg" alt="שקופית ${i + 1}" loading="lazy"></a>`
          + `<figcaption>${nn}${own ? ' · סגירה שלך' : ''}</figcaption></figure>`;
      }).join('')
    }</div>
  </section>`).join('');

  return `<!doctype html>
<html lang="he" dir="rtl">
<meta charset="utf-8">
<title>${onlyNew ? 'HotelMozil — חדשים' : 'HotelMozil — קרוסלות מוכנות'}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root { --bg:#0e1013; --card:#171a1f; --line:#272c33; --ink:#f2f4f7; --dim:#9aa3ad; --brand:#70d050; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--ink);
         font:16px/1.55 'Segoe UI', Arial, sans-serif; }
  header { padding:28px 24px 12px; border-bottom:1px solid var(--line); }
  h1 { margin:0 0 6px; font-size:22px; }
  header p { margin:0; color:var(--dim); font-size:14px; }
  section { padding:26px 24px 10px; border-bottom:1px solid var(--line); }
  h2 { margin:0 0 4px; font-size:19px; }
  .meta { color:var(--dim); font-size:13px; margin:0 0 14px; }
  .cap { background:var(--card); border:1px solid var(--line); border-radius:10px;
         padding:14px 16px; margin:0 0 18px; white-space:pre-wrap; font-size:15px; }
  .cap b { color:var(--brand); font-weight:600; }
  .strip { display:flex; gap:14px; overflow-x:auto; padding-bottom:16px; }
  figure { margin:0; flex:0 0 auto; }
  figure img { display:block; width:270px; height:480px; object-fit:cover;
               border-radius:12px; border:1px solid var(--line); background:#000; }
  figure.own img { border-color:#4a3a1f; }
  figcaption { color:var(--dim); font-size:12px; margin-top:6px; text-align:center; }
  footer { padding:18px 24px 40px; color:var(--dim); font-size:13px; }
  @media (max-width:700px) { figure img { width:200px; height:356px; } }
</style>
<header>
  <h1>${onlyNew ? 'מה שנבנה עכשיו' : 'קרוסלות מוכנות להעלאה'}</h1>
  <p>${onlyNew ? `${decks.length} קרוסלות מהסבב האחרון. ` : ''}לחיצה על תמונה פותחת אותה בגודל מלא. השתיים האחרונות בכל דק הן שקופיות הסגירה שלך.</p>
</header>
${sections}
<footer>נוצר אוטומטית בכל אריזה — הקבצים והכיתובים לידו בתיקיות.${onlyNew ? ' כל הקרוסלות: <a style="color:#70d050" href="review.html">review.html</a>' : ''}</footer>
</html>
`;
}
